// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package param

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type NewPerson struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewPerson) Reset()         { *m = NewPerson{} }
func (m *NewPerson) String() string { return proto.CompactTextString(m) }
func (*NewPerson) ProtoMessage()    {}
func (*NewPerson) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *NewPerson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewPerson.Unmarshal(m, b)
}
func (m *NewPerson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewPerson.Marshal(b, m, deterministic)
}
func (m *NewPerson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewPerson.Merge(m, src)
}
func (m *NewPerson) XXX_Size() int {
	return xxx_messageInfo_NewPerson.Size(m)
}
func (m *NewPerson) XXX_DiscardUnknown() {
	xxx_messageInfo_NewPerson.DiscardUnknown(m)
}

var xxx_messageInfo_NewPerson proto.InternalMessageInfo

func (m *NewPerson) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *NewPerson) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "param.Person")
	proto.RegisterType((*NewPerson)(nil), "param.NewPerson")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x48, 0x2c, 0x4a, 0xcc, 0x55, 0x72, 0xe3,
	0x62, 0x0b, 0x48, 0x2d, 0x2a, 0xce, 0xcf, 0x13, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x04, 0xb8, 0x98, 0x13, 0xd3, 0x53, 0x25,
	0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x40, 0x4c, 0x21, 0x31, 0x2e, 0xb6, 0xf4, 0xd4, 0xbc, 0x94,
	0xd4, 0x22, 0x09, 0x66, 0xb0, 0x3a, 0x28, 0x4f, 0xc9, 0x89, 0x8b, 0xd3, 0x2f, 0xb5, 0x1c, 0x6a,
	0x94, 0x2a, 0x17, 0x5b, 0x01, 0x98, 0x05, 0x36, 0x8c, 0xdb, 0x88, 0x57, 0x0f, 0x6c, 0x99, 0x1e,
	0x44, 0x3a, 0x08, 0x2a, 0x29, 0xc4, 0xc7, 0xc5, 0xe4, 0xe9, 0x02, 0x36, 0x9c, 0x33, 0x88, 0xc9,
	0xd3, 0xc5, 0xc8, 0x9e, 0x8b, 0x17, 0xa2, 0xc2, 0x23, 0x31, 0x2f, 0x25, 0x27, 0xb5, 0x48, 0x48,
	0x8f, 0x8b, 0xd3, 0x31, 0x25, 0x05, 0x6a, 0x28, 0xaa, 0x21, 0x52, 0x02, 0x50, 0x2e, 0xdc, 0x56,
	0x25, 0x86, 0x24, 0x36, 0xb0, 0xd7, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0xff, 0x7f,
	0xf7, 0xe8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonHandlerClient is the client API for PersonHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonHandlerClient interface {
	AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*NewPerson, error)
}

type personHandlerClient struct {
	cc *grpc.ClientConn
}

func NewPersonHandlerClient(cc *grpc.ClientConn) PersonHandlerClient {
	return &personHandlerClient{cc}
}

func (c *personHandlerClient) AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*NewPerson, error) {
	out := new(NewPerson)
	err := c.cc.Invoke(ctx, "/param.PersonHandler/AddPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonHandlerServer is the server API for PersonHandler service.
type PersonHandlerServer interface {
	AddPerson(context.Context, *Person) (*NewPerson, error)
}

func RegisterPersonHandlerServer(s *grpc.Server, srv PersonHandlerServer) {
	s.RegisterService(&_PersonHandler_serviceDesc, srv)
}

func _PersonHandler_AddPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonHandlerServer).AddPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/param.PersonHandler/AddPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonHandlerServer).AddPerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "param.PersonHandler",
	HandlerType: (*PersonHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPerson",
			Handler:    _PersonHandler_AddPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
